[memory]
max_token_limit = 500

[llama_index]
top_k = 3
chunk_size = 300
chunk_overlap = 30

[dataset.llm_finetune]
dir = "data/llm_finetune"
if_clean_texts = false
url_path = "data/llm_finetune/web_text_urls/urls.txt"
db_path = "data/llm_finetune/db"
pdf_dir = "data/llm_finetune/pdfs/"
youtube_urls = "data/llm_finetune/youtube_urls/urls.txt"

[dataset.explainable_ai]
dir = "data/explainable_ai"
if_clean_texts = false
url_path = "data/explainable_ai/web_text_urls/urls.txt"
db_path = "data/explainable_ai/db"

